#!/usr/bin/env bash
# Transfers a file from Holberton's client to another.
# Accepts four arguments:
#    The path to the file to be transferred.
#    The IP of the server to transfer the file to.
#    The username that scp connects with.
#    The path to the SSH private key that scp uses.

file_path="$1"
ip_address="$2"
username="$3"
key_path="$4"

if [ ! -f "$file_path" ]; then
  echo "Error: File '$file_path' not found."
  exit 1
fi

if [ ! -f "$key_path" ]; then
  echo "Error: SSH private key '$key_path' not found."
  exit 1
fi

echo "Transferring file to $username@$ip_address..."
scp -o StrictHostKeyChecking=no -i "$key_path" "$file_path" "$username@$ip_address":~

if [ $? -eq 0 ]; then
  echo "File transfer successful."
else
  echo "Error: File transfer failed."
fi
